[global]
developmentMode = false

[server]
port = 8501

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 2000

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
# Default: 200
maxMessageSize = 2000